[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Pin Node.js version used by Netlify build image
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"




